### ISSUE TITLE
Simplify query structure

### ISSUE THREAD

**Issue by kshvmdn** [kshvmdn/fsql#10]
- [x] Allow `SELECT` clause to be omitted (attribute should default to `all`) ([14344414](https://news.ycombinator.com/item?id=14344414), [14345753](https://news.ycombinator.com/item?id=14345753)).

   ```sh
   $ fsql "name, size, ... FROM . WHERE ..."
   $ fsql "FROM . WHERE ..."
   ```

- [x] Make `WHERE` clause optional (#8).
- [x] Quote-less queries:
  
  ```sh
  $ fsql SELECT \* FROM . WHERE ...
  $ fsql all FROM . WHERE ...
  ```

- [x] Make `FROM` clause optional, directory should default to the current directory (`./`).

**Comment by kshvmdn** [comment]
I've started working on this on [`refactor/query-structure`](https://github.com/kshvmdn/fsql/tree/refactor/query-structure).

**Comment by kshvmdn** [comment]
If you'd like to test, you'll have to build manually (since `go get` doesn't support fetching from non-master branches).

```sh
$ git clone https://github.com/kshvmdn/fsql.git $GOPATH/src/github.com/kshvmdn/fsql
$ cd $_
$ git fetch origin
$ git checkout -b refactor/query-structure origin/refactor/query-structure
$ go install
$ which fsql
$GOPATH/bin/fsql
```

**Comment by cdmckay** [comment]
Won't the shell expand the `*`?

**Comment by kshvmdn** [comment]
@cdmckay Hah, you're right. The `*` would have to be escaped as well, I think I'll add an example where that applies to the README as well.

**Comment by kshvmdn** [comment]
The PR for this is up (#16). Going to test over the next few hours and hopefully merge tonight. If you're interested in testing as well, follow https://github.com/kshvmdn/fsql/issues/10#issuecomment-301642980.

**Comment by kshvmdn** [comment]
Merged in https://github.com/kshvmdn/fsql/commit/a6c3339668ca477722d16238c1cf2f6e1616955d.

**Comment by lorenzhs** [comment]
@cdmckay in zsh you can do `alias fsql=noglob fsql` to disable globbing, then you could use `*` without escaping it.
