### ISSUE TITLE
Release Version to allow addition to Homebrew

### ISSUE THREAD

**Issue by snood1205** [kshvmdn/fsql#11]
This is a fantastic repo, and I'd love to add it to homebrew, but it needs a version to be added. If you could tag and release a version, that would be fantastic.

**Comment by kshvmdn** [comment]
Hey @snood1205! I'd love to get this up on Homebrew. I'm planning to release a version as soon as #10 is complete, should be a day or two now.

In the meantime, do you think you could provide me a little more info about releasing on Homebrew? More specifically the process of updating, would you be responsible for doing that or does it happen automatically based on tags/releases?

**Comment by kshvmdn** [comment]
@snood1205 Released [v0.1.0](https://github.com/kshvmdn/fsql/releases/tag/v0.1.0), should be good to go!

**Comment by kshvmdn** [comment]
An update on this:

I've got the formula ready (https://github.com/kshvmdn/homebrew-core/commit/c75775b53c7986547fef9349e33d0adbc1749d73). I wasn't aware that a repository needed to be at least 30 days old to be added to Homebrew, so it looks like I'll have to wait until then before making the PR.

**Comment by kshvmdn** [comment]
[v0.1.1](https://github.com/kshvmdn/fsql/releases/tag/v0.1.1) is now available on Homebrew!
