### ISSUE TITLE
tilde home expansion not working for me

### ISSUE THREAD

**Issue by hollerith** [kshvmdn/fsql#12]
fsql "SELECT name, size, time FROM ~/Documents WHERE name LIKE %.js AND time > 'May 15 2017 00 00'" 
2017/05/16 07:42:28 no such file or directory: ~/Documents

(exists with newer files there also namely fsql src)

/home/user/blah works fine.

**Comment by kshvmdn** [comment]
Hey @hollerith, thanks for reporting!

Should be fixed by b2c8e11999881e34a74cddffc34c0b4d8dd07336. Will keep this open until you (or someone else) can confirm that this is working fine now!

**Comment by hollerith** [comment]
Did a git pull and build - works great!

Thanks!
