### ISSUE TITLE
Binary Download Request

### ISSUE THREAD

**Issue by modulexcite** [kshvmdn/fsql#14]
Thank you for a great tool and sharing with the community; this is awesome.
Do you mind creating a binary/executable for Windows?

**Comment by kshvmdn** [comment]
I'll be drafting a full release later today or tomorrow (when #10 is complete), but I'll upload a Windows build until then.

I've never cross-compiled Go for Windows (and haven't actually used Windows for _quite some time_), so you might have to work with me on this.

- [windows_386.zip](https://github.com/kshvmdn/fsql/files/1005533/windows_386.zip) (32-bit x86)
- [windows_amd64.zip](https://github.com/kshvmdn/fsql/files/1005535/windows_amd64.zip) (64-bit x86)

---

Some notes for myself:

- https://golang.org/doc/install/source#environment
- http://stackoverflow.com/documentation/go/1020/cross-compilation/3298/compile-all-architectures-using-a-makefile#t=201705161851365224835

**Comment by modulexcite** [comment]
Great thanks for your quick response.
I have tested both 32 and 64-bit builds they seem to be working fine.

**64-bit Example (Searching for .txt files)**
```sh
fsql "SELECT name, size, time FROM . WHERE name LIKE %.txt AND time > 'Apr 01 2017 00 00'"
```
Output:
```
9632    May 11 10:55:48 ConEmu.txt
233145  Apr 18 06:44:20 history.txt
4129    Apr 18 06:44:05 settings.txt
4501    May 11 07:52:07 test.txt
256     May 16 10:38:31 new 2.txt
```

**32-bit Example (Searching for .txt files)**
```sh
fsql "SELECT name, size, time FROM . WHERE name LIKE %.txt AND time > 'Apr 01 2017 00 00'"
```
Output:
```
9632    May 11 10:55:48 ConEmu.txt
233145  Apr 18 06:44:20 history.txt
4129    Apr 18 06:44:05 settings.txt
4501    May 11 07:52:07 testg.txt
256     May 16 10:38:31 new 2.txt
```
