### ISSUE TITLE
How to show human readable file sizes?

### ISSUE THREAD

**Issue by applee** [kshvmdn/fsql#15]
It would be better to support some function to convert the size unit,  e.g. kb/mb/gb. So the sql would be as below
`fsql "select name, mb(size) from . where ...."`

**Comment by kshvmdn** [comment]
Great idea!

I'm thinking about introducing something called an _attribute modifier_, essentially used to modify attributes (this'll also be used for #3). I'll create an in-depth issue about this in the coming days.

I want the syntax to focus more on the actual attribute, so it doesn't feel like you're _using_ a function. My preliminary thought is to do something like this --

```sql
SELECT name::upper, size::mb FROM . WHERE time::iso ...
```

This will also allow attributes to have more than one modifier. Of course attributes can be selected without any modifier as well. The only downside that I see in doing it like this is that we're kind of moving away from SQL syntax (I'm not really sure if this is a problem).

Would love to hear your thoughts on this!

**Comment by applee** [comment]
It sounds so cool, as you said attribute modifier breaks SQL syntax, but functions not. I'm using another tool named [osquery](https://github.com/facebook/osquery), it looks like fully matched SQL syntax.

**Comment by tenitski** [comment]
Perhaps do it as SQL functions to maintain syntax compatibility:
```
SELECT UPPER(name), MB(size) FROM . WHERE ISO(time) = '...'
```

**Comment by kshvmdn** [comment]
@applee This is now implemented!

You can get a human-readable file size as follows:

```console
$ fsql "SELECT name, FORMAT(size, MB) FROM . WHERE ..."
```
