### ISSUE TITLE
Cannot start commands with `fsql`; have to use $GOPATH/bin/fsql

### ISSUE THREAD

**Issue by jkantner** [kshvmdn/fsql#18]
I seem to have installed fsql using `go get`, but I’m still not able to begin commands with `fsql`. I followed the steps as written. To use the program I have to change my directory to the bin folder where I installed Go and then drag the fsql Unix executable from Finder into Terminal. In other words, I ended up using `./bin/fsql <query>` instead of `fsql <query>`. Could there be any steps missing that would make `fsql <query>` valid?

**Comment by tracker1** [comment]
I wound up adding `~/go/bin` to my `$PATH` ... really seems to be a golang setup issue?

**Comment by kshvmdn** [comment]
Hey, thanks for giving fsql a try!

This seems to be a `$GOPATH` issue (`$GOPATH` points to the location of your Go workspace (the directory with the `bin`, `pkg`, and `src` directories)).

Try the following:

```sh
$ echo $GOPATH
/path/to/go/workspace
```

If that **doesn't** print anything, your `$GOPATH` isn't set yet, set it with this:

```sh
export GOPATH=/path/to/go/workspace
```

Now you can add `$GOPATH/bin` to your `$PATH`:

```sh
$ export PATH=$PATH:$GOPATH/bin
$ which fsql
$GOPATH/bin/fsql
```

You can permanently add it to your `$PATH` with the following:

```sh
$ echo "GOPATH=/path/to/go/workspace" >> ~/.bashrc
$ echo "export GOPATH" >> ~/.bashrc
$ echo "PATH=\$PATH:\$GOPATH/bin" >> ~/.bashrc
$ source ~/.bashrc
``` 

Let me know if that fixes it!

**Comment by jkantner** [comment]
Never mind. I copied and pasted the executable into usr/local/bin where I had installed other apps via npm, and the command worked. Thanks!

**Comment by kshvmdn** [comment]
No worries, glad to hear it's working!
