### ISSUE TITLE
Add -v Version output

### ISSUE THREAD

**Issue by tracker1** [kshvmdn/fsql#19]
Would be nice if `-v` and `--version` switches were supported, and printed the version and build date...

aside: should probably publish update instructions `go get -u -v ...` on the site, since I re-tried the -v alone and nothing happened... ;-)

**Comment by kshvmdn** [comment]
@tracker1 Thanks for the suggestions! Added in bc2b50ae4dd4307809144a05493bab8d592a14b3.
