### ISSUE TITLE
Difference between this and OSQuery

### ISSUE THREAD

**Issue by andrewhowdencom** [kshvmdn/fsql#2]
Hola! 

This seems to have a reasonable amount of overlap with the OSQuery project. Why write it anew?

**Comment by andrewhowdencom** [comment]
So, this was spam. I read "system" and not "filesystem". 

Closing as stupid. <3 Thanks man!

**Comment by kshvmdn** [comment]
Haha, no worries!

I actually hadn't heard about OSQuery before this, looks really cool -- thanks for letting me know about it! 😄
