### ISSUE TITLE
Go vendoring?

### ISSUE THREAD

**Issue by ilovezfs** [kshvmdn/fsql#28]
Would you be willing to start using the Go vendor directory or one of the other Go vendor systems so that we can avoid go resource blocks in the Homebrew formula?

I noticed while doing the upgrade from 0.1.1 to 0.2.0 that fsql no longer builds unless I add a go resource block for `gopkg.in/oleiade/lane.v1`.

It would be much appreciated if we could avoid this in the formula, as we're trying to eliminate the use of go resource blocks, so having to add them to a formula that doesn't currently need them is :(

**Comment by kshvmdn** [comment]
@ilovezfs Done!

**Comment by ilovezfs** [comment]
Thanks! Could I convince you to create a new tag too? :innocent:

**Comment by kshvmdn** [comment]
@ilovezfs Published [v0.2.1](https://github.com/kshvmdn/fsql/releases/tag/v0.2.1)! 😄

**Comment by ilovezfs** [comment]
Perfect! Thank you :)

**Comment by ilovezfs** [comment]
@kshvmdn I've updated https://github.com/Homebrew/homebrew-core/pull/14404 to be for 0.2.1 :)
