### ISSUE TITLE
Add support for ISO 8601 datetime format

### ISSUE THREAD

**Issue by njy** [kshvmdn/fsql#3]

**Comment by kshvmdn** [comment]
Thanks for the suggestion!

Golang's [time](https://golang.org/pkg/time/#pkg-constants) package has direct support for RFC3339 ([which is very similar to ISO 8601](http://stackoverflow.com/a/522281/4639651)), so it might be easier to use that instead.

I'm not sure if it'll be possible to parse the format from the value though. Do you have any ideas as to how we could differentiate this format with the currently-supported format?

Perhaps introduce an `isotime` attribute?

```sql
... WHERE isotime > 2006-01-02T15:04:05Z07:00 ...
```

**Comment by njy** [comment]
Thanks for the fast response: I'm not that much into creating a new fake attribute.
Maybe something like a functions-like syntax may be more flexible, but I don't know how hard it may be to support such a syntax, something like:

`... WHERE time > iso('2008-09-15T15:53:00') `

Thoughts?

**Comment by kshvmdn** [comment]
I like it. Definitely better than my idea.

It should be possible, might have to use something other than parens (maybe `iso::2008-09-15T15:53:00`), I'll play around with it and let you know!
