### ISSUE TITLE
Respecting attribute order

### ISSUE THREAD

**Issue by timnashcouk** [kshvmdn/fsql#34]
In the scenario:
`fsql "select FULLPATH(name), hash from...`
I would expect the return to be:
/path hash
instead it's hash /path

running the latest version available via brew.
`% fsql -v                                                                                                           
fsql version 0.3.x, built off master`

**Comment by kshvmdn** [comment]
Thanks for the issue! I agree with you.

The order was originally chosen to match that of `ls -l` (i.e. `[mode] [size] [time] [name]`), but I think as we introduce new attributes, it'd be better to respect the requested order.
