### ISSUE TITLE
Excluding directories also excludes similarly-named files

### ISSUE THREAD

**Issue by kshvmdn** [kshvmdn/fsql#5]
For example, excluding `.git` (with `-.git`) results in `.gitignore` not being listed.

This can be resolved with excluding with `-.git/` instead, but then `.git` is listed.

**Comment by jonesbrianc26** [comment]
Mind if I take this one? I see you have a branch with some refactorings. Not sure if you've tackled it there, but I've identified that it's a problem with the logic in:
`main::containsAny(exclusions []string, path string)`

**Comment by jonesbrianc26** [comment]
Very cool project btw!

**Comment by kshvmdn** [comment]
Resolved in #21! 😄
