### ISSUE TITLE
Improve support for directories/files in current path...

### ISSUE THREAD

**Issue by tracker1** [kshvmdn/fsql#6]
This works...

    fsql "SELECT * FROM ./_src WHERE name LIKE %.js"

this does not...

    fsql "SELECT * FROM _src WHERE name LIKE %.js"

**Comment by kshvmdn** [comment]
Thanks for reporting!

Should be resolved as of d2f0ce05c716a7c178d61bd4d69b0d1e1c08f241, let me know if it's still not working.

**Comment by kshvmdn** [comment]
Going to keep this open until confirmation that it's fine.

**Comment by tracker1** [comment]
Working... :-)
