### ISSUE TITLE
Support globs in FROM

### ISSUE THREAD

**Issue by tracker1** [kshvmdn/fsql#7]
I know there's intentionally `WHERE name LIKE`, but would be nice to have glob support in the FROM clause directly.... `FROM ./foo/**/*.js ...`

**Comment by kshvmdn** [comment]
Added in c1f275b559be5a5f377cd771d9aeeff4b65af7b1, thanks for the suggestion @tracker1!

Do note that it only supports usage of `*` and `?` right now (i.e. no `[abc]` / `[a-z]`). I'll create another issue to cover that though (it relates to how the tokenizer reads bracketed text).
