### ISSUE TITLE
Hash support

### ISSUE THREAD

**Issue by kdeenanauth** [kshvmdn/fsql#9]
This might be out of scope, but it would be handy to generate the SHA-1 (or other hashes) to output and/or compare with another directory of files (when subqueries are implemented).

**Comment by jonesbrianc26** [comment]
This doesn't look too bad to get in, I haven't looked to much at the parsing logic but should be able to follow the logic for the other key words. Anything other than SHA-1 We'd like to see?

**Comment by kshvmdn** [comment]
@jonesbrianc26 Sounds good!

Let's do this by introducing a new attribute, `hash`. I think the best way to specify which algorithm to use would would be an attribute modifier, so perhaps

```sql
SELECT SHA1(hash) ...
... WHERE SHA256(hash) = ...
```

or

```sql
SELECT FORMAT(hash, SHA1) ...
... WHERE FORMAT(hash, SHA256) ...
```

For the time being, lets stick with SHA-1 and see how that goes ([`crypto/sha1`](https://golang.org/pkg/crypto/sha1/) will probably be useful for this). We should be able to easily abstract this to support [multiple different algorithms](https://golang.org/pkg/crypto/#pkg-subdirectories) in the future.

**Comment by jonesbrianc26** [comment]
Turns out this isn't too bad, Though will probably need to rethink the output function a little bit to be smarter with spacing.with multiple attributes and a hash a singe `\t` no longer suffices".

We should probably justify the output similar to how `go fmt` justifies structs. what do you think?

**Comment by kshvmdn** [comment]
Awesome!

The original output format was meant to match that of `ls -l`, I think we can stick with that?

```
[mode] [size] [time] [hash] [name]
```

Also, I think by default, we should show a truncated version of the hash (maybe 7-10 characters, like Git), and we can include a `FULL` function to show the full hash (perhaps even a `TRUNCATE(, n)` function to specify how many characters to show?).

**Comment by jonesbrianc26** [comment]
perhaps just `{hashtype}(hash, {})` though, TRUNCATE(,n) could be useful in general and would be a extremely reusable function so it may be better to use that under the hood.

**Comment by kshvmdn** [comment]
You're right, that works better!

If `n` isn't provided, let's default it to 7 for the time being, just so the output of `all` doesn't overflow.

**Comment by jonesbrianc26** [comment]
Also, as far as formatting goes, what would you like to display in place of the hash for directories?

Currently I'm displaying 1 `-` for every character in the hash to preserve equal spacing, maybe once I get the PR up we can discuss that a bit more.

**Comment by kshvmdn** [comment]
Sounds good to me!

**Comment by kshvmdn** [comment]
Done in #31 – currently only supports SHA-1, feel free to suggest other functions.
